#!/usr/bin/env python3
"""daily_report.py — write BOARD.md: today's heaviest legs + candidate tickets.

Runs after pull_feeds.py in the Action. Everything in BOARD.md is derived from
the feed files in this repo, so the report and the board cannot disagree.

Two standing facts are printed at the top of every report, on purpose:
  * FanDuel posts NO first-five totals through this API (verified three ways
    on 2026-08-03) — the F5 family cannot appear here no matter how good the
    slate is;
  * every ticket is a candidate, not an instruction: check each leg against
    the FanDuel app before placing. Prices move; this file has a timestamp.
"""
import math, os, subprocess, sys, datetime as dt
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import board
from board import build
from times import et


def _today_et():
    try:
        from zoneinfo import ZoneInfo
        return dt.datetime.now(ZoneInfo("America/New_York")).date()
    except Exception:
        return dt.datetime.now(dt.timezone.utc).date()


def next_sunday_et():
    today = _today_et()
    return (today + dt.timedelta(days=(6 - today.weekday()) % 7)).isoformat()


def heaviest_table(horizon, n=25):
    markets = build('FanDuel', no_plus=True, min_price=350,
                    cutoff=board._utcnow(), horizon=horizon)
    legs = sorted((o for v in markets.values() for o in v),
                  key=lambda o: -o['p'])[:n]
    if not legs:
        return "_(no legs at -350 or heavier inside the horizon)_\n"
    out = ["| # | start (ET) | leg | price | p(hit) | fam |",
           "|---|---|---|---|---|---|"]
    for i, o in enumerate(legs, 1):
        out.append(f"| {i} | {et(o['t'])} | {o['lab']} | {o['price']:+d} "
                   f"| {o['p']*100:.1f}% | {o['fam']} |")
    return "\n".join(out) + "\n"


def try_ticket(title, target, flags, legs_sweep):
    """Run solve2 over a descending legs sweep; keep the first ticket found."""
    for legs in legs_sweep:
        r = subprocess.run(
            [sys.executable, os.path.join(HERE, "solve2.py"), "FanDuel",
             str(target), f"--legs={legs}"] + flags,
            capture_output=True, text=True)
        if r.returncode == 0 and "joint hit probability" in r.stdout:
            body = r.stdout.split("=" * 20, 1)[-1]
            return (f"### {title}\n\n```\n"
                    + ("=" * 20) + body.strip() + "\n```\n")
    return f"### {title}\n\n_No ticket meets these constraints today._\n"


def main():
    ts = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sunday = next_sunday_et()
    md = [f"# Board report — {ts}",
          "",
          "Auto-generated by the daily refresh. **Check every leg against the "
          "FanDuel app before placing anything** — prices move, and this file "
          "has a timestamp. FanDuel posts **no first-five totals** through "
          "this API, so no F5 legs can appear below regardless of the slate.",
          "",
          f"## Heaviest favorites through Sunday {sunday} (-350 or better, de-vigged)",
          "",
          heaviest_table(sunday),
          "",
          "## Candidate tickets",
          "",
          try_ticket(f"~21x through Sunday {sunday} (max hit probability)",
                     21, [f"--by={sunday}", "--minprice=350", "--nofam=ML"],
                     range(22, 13, -1)),
          "",
          try_ticket(f"~12x through Sunday {sunday}, baseball capped at 4 legs",
                     12, [f"--by={sunday}", "--minprice=350", "--nofam=ML",
                          "--maxmlb=4"],
                     range(20, 11, -1)),
          "",
          try_ticket("~10x tonight only (everything settles today, ET)",
                     10, [f"--by={_today_et().isoformat()}", "--minprice=300",
                          "--nofam=ML"],
                     range(16, 7, -1)),
          ""]
    with open(os.path.join(HERE, "BOARD.md"), "w") as fh:
        fh.write("\n".join(md))
    print("wrote BOARD.md")


if __name__ == "__main__":
    main()
