"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-09-30 15:28Z from The Odds API, FanDuel prices only.
GAME|POINT|OVER|UNDER — FanDuel first-five-inning alternate totals, market key alternate_totals_1st_5_innings (NOT totals_h1, which is empty for MLB and once produced a false 'F5 does not exist' verdict). Shares the ('GT', game) market key with the full-game ladder in board.py, so a solver takes at most one total per game."""

F5_RAW = """
PHI@ATL|0.5|-3000|880
PHI@ATL|1.5|-580|360
PHI@ATL|2.5|-240|174
PHI@ATL|3.5|-118|-112
PHI@ATL|4.5|152|-205
PHI@ATL|5.5|235|-340
PHI@ATL|6.5|390|-650
PHI@ATL|7.5|580|-1200
PHI@ATL|8.5|880|-3000
PHI@ATL|9.5|1200|-5000
CWS@HOU|0.5|-3500|920
CWS@HOU|1.5|-700|410
CWS@HOU|2.5|-300|210
CWS@HOU|3.5|-152|114
CWS@HOU|4.5|116|-154
CWS@HOU|5.5|194|-270
CWS@HOU|6.5|300|-450
CWS@HOU|7.5|450|-800
CWS@HOU|8.5|640|-1450
CWS@HOU|9.5|920|-3500
CWS@HOU|10.5|1280|-7000
BOS@NYY|0.5|-3500|920
BOS@NYY|1.5|-600|370
BOS@NYY|2.5|-245|178
BOS@NYY|3.5|-118|-112
BOS@NYY|4.5|152|-205
BOS@NYY|5.5|240|-350
BOS@NYY|6.5|390|-650
BOS@NYY|7.5|580|-1200
BOS@NYY|8.5|850|-3000
BOS@NYY|9.5|1200|-5000
CHC@SD|0.5|-4500|1100
CHC@SD|1.5|-800|450
CHC@SD|2.5|-310|220
CHC@SD|3.5|-154|116
CHC@SD|4.5|118|-158
CHC@SD|5.5|194|-270
CHC@SD|6.5|310|-470
CHC@SD|7.5|470|-850
CHC@SD|8.5|700|-1800
CHC@SD|9.5|1000|-4000
"""
