"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-14 00:06Z from The Odds API, FanDuel prices only.
GAME|POINT|OVER|UNDER — FanDuel first-five-inning alternate totals, market key alternate_totals_1st_5_innings (NOT totals_h1, which is empty for MLB and once produced a false 'F5 does not exist' verdict). Shares the ('GT', game) market key with the full-game ladder in board.py, so a solver takes at most one total per game."""

F5_RAW = """
PHI@MIN|2.5|-2000|850
PHI@MIN|3.5|-475|300
PHI@MIN|4.5|-220|140
PHI@MIN|5.5|-120|-135
PHI@MIN|6.5|155|-230
PHI@MIN|7.5|260|-400
PHI@MIN|8.5|430|-700
PHI@MIN|9.5|650|-1250
PHI@MIN|10.5|1000|-2500
TEX@LAA|2.5|-275|198
TEX@LAA|3.5|-146|110
TEX@LAA|4.5|122|-162
TEX@LAA|5.5|198|-275
TEX@LAA|6.5|310|-470
TEX@LAA|7.5|490|-900
TEX@LAA|8.5|700|-1800
TEX@LAA|9.5|920|-3500
TEX@LAA|10.5|1280|-7000
MIL@LAD|2.5|-420|280
MIL@LAD|3.5|-205|152
MIL@LAD|4.5|-114|-114
MIL@LAD|5.5|146|-198
MIL@LAD|6.5|225|-320
MIL@LAD|7.5|350|-550
MIL@LAD|8.5|520|-1000
MIL@LAD|9.5|700|-1800
MIL@LAD|10.5|920|-3500
"""
