"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-13 18:53Z from The Odds API, FanDuel prices only.
GAME|POINT|OVER|UNDER — FanDuel first-five-inning alternate totals, market key alternate_totals_1st_5_innings (NOT totals_h1, which is empty for MLB and once produced a false 'F5 does not exist' verdict). Shares the ('GT', game) market key with the full-game ladder in board.py, so a solver takes at most one total per game."""

F5_RAW = """
SEA@NYY|2.5|260|-400
SEA@NYY|3.5|600|-1100
BOS@TOR|2.5|-340|235
BOS@TOR|3.5|-174|130
BOS@TOR|4.5|102|-136
BOS@TOR|5.5|174|-240
BOS@TOR|6.5|270|-400
BOS@TOR|7.5|400|-670
BOS@TOR|8.5|630|-1400
BOS@TOR|9.5|880|-3000
BOS@TOR|10.5|1200|-5000
CHC@WSH|2.5|-400|270
CHC@WSH|3.5|-198|146
CHC@WSH|4.5|-108|-122
CHC@WSH|5.5|154|-210
CHC@WSH|6.5|235|-340
CHC@WSH|7.5|370|-600
CHC@WSH|8.5|550|-1100
CHC@WSH|9.5|800|-2200
CHC@WSH|10.5|1100|-4500
PHI@MIN|2.5|-440|290
PHI@MIN|3.5|-225|164
PHI@MIN|4.5|-125|-106
PHI@MIN|5.5|138|-186
PHI@MIN|6.5|220|-310
PHI@MIN|7.5|320|-490
PHI@MIN|8.5|490|-900
PHI@MIN|9.5|680|-1600
PHI@MIN|10.5|920|-3500
TEX@LAA|2.5|-300|210
TEX@LAA|3.5|-154|116
TEX@LAA|4.5|118|-158
TEX@LAA|5.5|194|-270
TEX@LAA|6.5|300|-450
TEX@LAA|7.5|430|-750
TEX@LAA|8.5|640|-1450
TEX@LAA|9.5|920|-3500
TEX@LAA|10.5|1260|-6000
MIL@LAD|2.5|-420|280
MIL@LAD|3.5|-210|154
MIL@LAD|4.5|-118|-112
MIL@LAD|5.5|148|-200
MIL@LAD|6.5|230|-330
MIL@LAD|7.5|350|-550
MIL@LAD|8.5|520|-1000
MIL@LAD|9.5|750|-2000
MIL@LAD|10.5|1000|-4500
"""
