"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-06 23:45Z from The Odds API, FanDuel prices only.
UTC|AWAY@HOME|Team ML|price|opp_price. Both sides of every game: the de-vig needs the pair. 'No moneylining baseball teams' is enforced at solve time with --nofam=ML, not by hiding the market."""

MLBML_RAW = """
2026-08-06T22:06Z|WSH@PHI|Philadelphia Phillies ML|-4000|2700
2026-08-06T22:06Z|WSH@PHI|Washington Nationals ML|2700|-4000
2026-08-06T23:11Z|CWS@BOS|Boston Red Sox ML|-150|135
2026-08-06T23:11Z|CWS@BOS|Chicago White Sox ML|135|-150
2026-08-06T23:16Z|MIA@ATL|Atlanta Braves ML|-195|170
2026-08-06T23:16Z|MIA@ATL|Miami Marlins ML|170|-195
2026-08-06T23:41Z|MIN@KC|Kansas City Royals ML|-150|135
2026-08-06T23:41Z|MIN@KC|Minnesota Twins ML|135|-150
2026-08-07T01:41Z|SD@ARI|Arizona Diamondbacks ML|-104|-104
2026-08-07T01:41Z|SD@ARI|San Diego Padres ML|-104|-104
"""
