"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-04 22:05Z from The Odds API, FanDuel prices only.
UTC|AWAY@HOME|Team ML|price|opp_price. Both sides of every game: the de-vig needs the pair. 'No moneylining baseball teams' is enforced at solve time with --nofam=ML, not by hiding the market."""

MLBML_RAW = """
2026-08-04T22:36Z|LAA@BAL|Baltimore Orioles ML|-148|138
2026-08-04T22:36Z|LAA@BAL|Los Angeles Angels ML|138|-148
2026-08-04T22:40Z|ATH@CIN|Athletics ML|122|-132
2026-08-04T22:40Z|ATH@CIN|Cincinnati Reds ML|-132|122
2026-08-04T22:40Z|NYM@CLE|Cleveland Guardians ML|-126|116
2026-08-04T22:40Z|NYM@CLE|New York Mets ML|116|-126
2026-08-04T22:40Z|WSH@PHI|Philadelphia Phillies ML|-300|260
2026-08-04T22:40Z|WSH@PHI|Washington Nationals ML|260|-300
2026-08-04T23:06Z|STL@NYY|New York Yankees ML|-190|176
2026-08-04T23:06Z|STL@NYY|St. Louis Cardinals ML|176|-190
2026-08-04T23:11Z|CWS@BOS|Boston Red Sox ML|-138|128
2026-08-04T23:11Z|CWS@BOS|Chicago White Sox ML|128|-138
2026-08-04T23:16Z|MIA@ATL|Atlanta Braves ML|-142|132
2026-08-04T23:16Z|MIA@ATL|Miami Marlins ML|132|-142
2026-08-04T23:40Z|PIT@MIL|Milwaukee Brewers ML|-142|132
2026-08-04T23:40Z|PIT@MIL|Pittsburgh Pirates ML|132|-142
2026-08-04T23:41Z|MIN@KC|Kansas City Royals ML|130|-140
2026-08-04T23:41Z|MIN@KC|Minnesota Twins ML|-140|130
2026-08-05T00:06Z|LAD@CHC|Chicago Cubs ML|176|-190
2026-08-05T00:06Z|LAD@CHC|Los Angeles Dodgers ML|-190|176
2026-08-05T00:06Z|SF@TEX|San Francisco Giants ML|176|-190
2026-08-05T00:06Z|SF@TEX|Texas Rangers ML|-190|176
2026-08-05T00:10Z|TOR@HOU|Houston Astros ML|-136|126
2026-08-05T00:10Z|TOR@HOU|Toronto Blue Jays ML|126|-136
2026-08-05T00:41Z|TB@COL|Colorado Rockies ML|154|-166
2026-08-05T00:41Z|TB@COL|Tampa Bay Rays ML|-166|154
2026-08-05T01:41Z|SD@ARI|Arizona Diamondbacks ML|-114|104
2026-08-05T01:41Z|SD@ARI|San Diego Padres ML|104|-114
2026-08-05T01:41Z|DET@SEA|Detroit Tigers ML|110|-120
2026-08-05T01:41Z|DET@SEA|Seattle Mariners ML|-120|110
"""
