"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-10 21:33Z from The Odds API, FanDuel prices only.
UTC|AWAY@HOME|Team ML|price|opp_price. Both sides of every game: the de-vig needs the pair. 'No moneylining baseball teams' is enforced at solve time with --nofam=ML, not by hiding the market."""

MLBML_RAW = """
2026-08-10T23:07Z|BOS@TOR|Boston Red Sox ML|-156|144
2026-08-10T23:07Z|BOS@TOR|Toronto Blue Jays ML|144|-156
2026-08-10T23:15Z|NYM@ATL|Atlanta Braves ML|-140|130
2026-08-10T23:15Z|NYM@ATL|New York Mets ML|130|-140
2026-08-10T23:40Z|BAL@MIN|Baltimore Orioles ML|-104|-104
2026-08-10T23:40Z|BAL@MIN|Minnesota Twins ML|-104|-104
2026-08-10T23:46Z|PHI@STL|Philadelphia Phillies ML|-112|104
2026-08-10T23:46Z|PHI@STL|St. Louis Cardinals ML|104|-112
2026-08-11T01:38Z|TEX@LAA|Los Angeles Angels ML|100|-108
2026-08-11T01:38Z|TEX@LAA|Texas Rangers ML|-108|100
2026-08-11T01:40Z|COL@ARI|Arizona Diamondbacks ML|-194|180
2026-08-11T01:40Z|COL@ARI|Colorado Rockies ML|180|-194
2026-08-11T01:41Z|TB@ATH|Athletics ML|144|-156
2026-08-11T01:41Z|TB@ATH|Tampa Bay Rays ML|-156|144
2026-08-11T01:41Z|MIL@SD|Milwaukee Brewers ML|-114|104
2026-08-11T01:41Z|MIL@SD|San Diego Padres ML|104|-114
2026-08-11T01:46Z|HOU@SF|Houston Astros ML|-142|132
2026-08-11T01:46Z|HOU@SF|San Francisco Giants ML|132|-142
2026-08-11T02:10Z|KC@LAD|Kansas City Royals ML|240|-270
2026-08-11T02:10Z|KC@LAD|Los Angeles Dodgers ML|-270|240
"""
