"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-19 17:37Z from The Odds API, FanDuel prices only.
Book|card|favourite|fav_price|dog_price. ONE LINE PER BOUT -- board.py builds both sides from it; a second line would mint a second market for the same fight. No model involved: the UFC forward test went 0-for-5 against the market on disagreements."""

MMA_RAW = """
FanDuel|MMA 08-22|Nasrat Haqparast|-125|-102
FanDuel|MMA 08-22|Gauge Young|-132|104
FanDuel|MMA 08-22|Jackson McVey|-186|144
FanDuel|MMA 08-22|Lerryan Douglas|-410|290
FanDuel|MMA 08-22|Shamil Gaziev|-148|116
FanDuel|MMA 08-22|Shanelle Dyer|-850|500
FanDuel|MMA 08-22|Márcio Barbosa|-1000|560
FanDuel|MMA 08-22|Anthony Wint|-1400|680
FanDuel|MMA 08-22|Carli Judice|-620|400
FanDuel|MMA 08-22|Mason Jones|-295|220
FanDuel|MMA 08-22|Reinier de Ridder|-400|285
FanDuel|MMA 08-22|Vitor Petrino|-160|124
FanDuel|MMA 08-22|Anthony Hernandez|-184|142
FanDuel|MMA 08-29|Umar Nurmagomedov|-520|350
"""
