"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-06 23:45Z from The Odds API, FanDuel prices only.
Book|card|favourite|fav_price|dog_price. ONE LINE PER BOUT -- board.py builds both sides from it; a second line would mint a second market for the same fight. No model involved: the UFC forward test went 0-for-5 against the market on disagreements."""

MMA_RAW = """
FanDuel|MMA 08-07|Denis Goltsov|-400|300
FanDuel|MMA 08-07|Lewis McGrillen|-950|590
FanDuel|MMA 08-07|Trey Waters|-235|194
FanDuel|MMA 08-07|Maxwell Djantou Nana|-156|132
FanDuel|MMA 08-07|Jonathan Martin|-136|114
FanDuel|MMA 08-07|Valentin Moldavsky|-500|360
FanDuel|MMA 08-07|Landry Ward|-310|240
FanDuel|MMA 08-07|Cheyanne Bowers|-340|260
FanDuel|MMA 08-07|Cheyden Leialoha|-265|210
FanDuel|MMA 08-07|Josh Fremd|-430|320
FanDuel|MMA 08-07|Aaron Jeffery|-192|154
FanDuel|MMA 08-07|Dovletdzhan Yagshimuradov|-188|152
FanDuel|MMA 08-07|Bryan Battle|-142|116
FanDuel|MMA 08-08|Carol Foro|-310|235
FanDuel|MMA 08-08|Juliana Miller|-310|240
FanDuel|MMA 08-08|Miles Johns|-170|138
FanDuel|MMA 08-08|Manoel Sousa|-300|235
FanDuel|MMA 08-08|Diyar Nurgozhay|-160|130
FanDuel|MMA 08-08|Louie Sutherland|-188|152
FanDuel|MMA 08-08|Steven Asplund|-300|235
FanDuel|MMA 08-08|Ty Miller|-430|300
FanDuel|MMA 08-08|Alexia Thainara|-265|200
FanDuel|MMA 08-08|Yadier DelValle|-800|480
FanDuel|MMA 08-08|Carlos Diego Ferreira|-186|144
FanDuel|MMA 08-08|Quillan Salkilld|-154|120
FanDuel|MMA 08-15|Mackenzie Dern|-265|200
FanDuel|MMA 08-16|Islam Makhachev|-390|280
"""
