"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-04 22:05Z from The Odds API, FanDuel prices only.
Book|card|favourite|fav_price|dog_price. ONE LINE PER BOUT -- board.py builds both sides from it; a second line would mint a second market for the same fight. No model involved: the UFC forward test went 0-for-5 against the market on disagreements."""

MMA_RAW = """
FanDuel|MMA 08-08|Miles Johns|-170|132
FanDuel|MMA 08-08|Louie Sutherland|-162|126
FanDuel|MMA 08-08|Alexia Thainara|-265|200
FanDuel|MMA 08-08|Ty Miller|-350|255
FanDuel|MMA 08-08|Carlos Diego Ferreira|-186|144
FanDuel|MMA 08-08|Diyar Nurgozhay|-164|128
FanDuel|MMA 08-08|Yadier DelValle|-720|450
FanDuel|MMA 08-08|Steven Asplund|-265|200
FanDuel|MMA 08-08|Juliana Miller|-290|215
FanDuel|MMA 08-08|Manoel Sousa|-265|200
FanDuel|MMA 08-08|Quillan Salkilld|-154|120
FanDuel|MMA 08-15|Mackenzie Dern|-265|200
FanDuel|MMA 08-16|Islam Makhachev|-390|280
"""
