"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-04 19:05Z from The Odds API, FanDuel prices only.
START holds TODAY'S MLB slate only (one game key per day -- a doubleheader's second game is dropped upstream). FIGHT_START is keyed by the favourite named in mma.py, ONE entry per bout."""

START = {
    "LAA@BAL": "2026-08-04T22:36Z",
    "ATH@CIN": "2026-08-04T22:40Z",
    "NYM@CLE": "2026-08-04T22:40Z",
    "WSH@PHI": "2026-08-04T22:40Z",
    "STL@NYY": "2026-08-04T23:06Z",
    "CWS@BOS": "2026-08-04T23:11Z",
    "MIA@ATL": "2026-08-04T23:16Z",
    "PIT@MIL": "2026-08-04T23:40Z",
    "MIN@KC": "2026-08-04T23:41Z",
    "LAD@CHC": "2026-08-05T00:06Z",
    "SF@TEX": "2026-08-05T00:06Z",
    "TOR@HOU": "2026-08-05T00:10Z",
    "TB@COL": "2026-08-05T00:41Z",
    "SD@ARI": "2026-08-05T01:41Z",
    "DET@SEA": "2026-08-05T01:41Z",
}

FIGHT_START = {
    "Miles Johns": "2026-08-08T21:40Z",
    "Alexia Thainara": "2026-08-09T00:00Z",
    "Carlos Diego Ferreira": "2026-08-09T00:00Z",
    "Diyar Nurgozhay": "2026-08-09T00:00Z",
    "Juliana Miller": "2026-08-09T00:00Z",
    "Manoel Sousa": "2026-08-09T00:00Z",
    "Quillan Salkilld": "2026-08-09T00:00Z",
    "Steven Asplund": "2026-08-09T00:00Z",
    "Ty Miller": "2026-08-09T00:00Z",
    "Yadier DelValle": "2026-08-09T00:00Z",
    "Louie Sutherland": "2026-08-09T01:15Z",
    "Mackenzie Dern": "2026-08-16T03:00Z",
    "Islam Makhachev": "2026-08-16T04:00Z",
}

def et(utc):
    """UTC string -> Eastern wall clock, WITH THE DATE. Fixed -4 offset; fine
    inside the EDT window this board lives in. The date is not decoration:
    three 'Sat's on one ticket can be three different Saturdays."""
    from datetime import datetime, timedelta
    d = datetime.strptime(utc, "%Y-%m-%dT%H:%MZ") - timedelta(hours=4)
    return d.strftime("%a %-m/%-d %-I:%M%p").replace("AM", "am").replace("PM", "pm")
