"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-09 21:23Z from The Odds API, FanDuel prices only.
START holds TODAY'S MLB slate only (one game key per day -- a doubleheader's second game is dropped upstream). FIGHT_START is keyed by the favourite named in mma.py, ONE entry per bout."""

START = {
    "CLE@CWS": "2026-08-09T18:10Z",
    "MIN@MIL": "2026-08-09T18:10Z",
    "DET@SF": "2026-08-09T20:06Z",
    "LAD@ARI": "2026-08-09T20:10Z",
    "TB@SEA": "2026-08-09T20:11Z",
    "HOU@SD": "2026-08-10T00:20Z",
}

FIGHT_START = {
    "Donte Johnson": "2026-08-16T02:00Z",
    "Esteban Ribovics": "2026-08-16T02:00Z",
    "Jalin Turner": "2026-08-16T02:00Z",
    "Joel Alvarez": "2026-08-16T02:00Z",
    "Lucas Fernando": "2026-08-16T02:00Z",
    "Mansur Abdul-Malik": "2026-08-16T02:00Z",
    "Myktybek Orolbai": "2026-08-16T02:00Z",
    "Neil Magny": "2026-08-16T02:00Z",
    "Tresean Gore": "2026-08-16T02:00Z",
    "Mackenzie Dern": "2026-08-16T02:45Z",
    "Islam Makhachev": "2026-08-16T03:30Z",
}

def et(utc):
    """UTC string -> Eastern wall clock, WITH THE DATE. Fixed -4 offset; fine
    inside the EDT window this board lives in. The date is not decoration:
    three 'Sat's on one ticket can be three different Saturdays."""
    from datetime import datetime, timedelta
    d = datetime.strptime(utc, "%Y-%m-%dT%H:%MZ") - timedelta(hours=4)
    return d.strftime("%a %-m/%-d %-I:%M%p").replace("AM", "am").replace("PM", "pm")
