"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-06 23:45Z from The Odds API, FanDuel prices only.
START holds TODAY'S MLB slate only (one game key per day -- a doubleheader's second game is dropped upstream). FIGHT_START is keyed by the favourite named in mma.py, ONE entry per bout."""

START = {
    "WSH@PHI": "2026-08-06T22:06Z",
    "CWS@BOS": "2026-08-06T23:11Z",
    "MIA@ATL": "2026-08-06T23:16Z",
    "MIN@KC": "2026-08-06T23:41Z",
    "SD@ARI": "2026-08-07T01:41Z",
}

FIGHT_START = {
    "Denis Goltsov": "2026-08-07T13:35Z",
    "Lewis McGrillen": "2026-08-07T14:35Z",
    "Trey Waters": "2026-08-07T22:40Z",
    "Maxwell Djantou Nana": "2026-08-07T23:05Z",
    "Jonathan Martin": "2026-08-07T23:30Z",
    "Valentin Moldavsky": "2026-08-07T23:55Z",
    "Landry Ward": "2026-08-08T00:20Z",
    "Cheyanne Bowers": "2026-08-08T00:45Z",
    "Cheyden Leialoha": "2026-08-08T01:10Z",
    "Josh Fremd": "2026-08-08T02:10Z",
    "Aaron Jeffery": "2026-08-08T03:00Z",
    "Dovletdzhan Yagshimuradov": "2026-08-08T03:25Z",
    "Bryan Battle": "2026-08-08T03:50Z",
    "Carol Foro": "2026-08-08T21:10Z",
    "Juliana Miller": "2026-08-08T21:35Z",
    "Miles Johns": "2026-08-08T21:40Z",
    "Manoel Sousa": "2026-08-08T22:25Z",
    "Diyar Nurgozhay": "2026-08-08T23:15Z",
    "Louie Sutherland": "2026-08-08T23:15Z",
    "Steven Asplund": "2026-08-08T23:40Z",
    "Ty Miller": "2026-08-09T00:15Z",
    "Alexia Thainara": "2026-08-09T00:45Z",
    "Yadier DelValle": "2026-08-09T01:15Z",
    "Carlos Diego Ferreira": "2026-08-09T01:45Z",
    "Quillan Salkilld": "2026-08-09T02:15Z",
    "Mackenzie Dern": "2026-08-16T03:00Z",
    "Islam Makhachev": "2026-08-16T04:00Z",
}

def et(utc):
    """UTC string -> Eastern wall clock, WITH THE DATE. Fixed -4 offset; fine
    inside the EDT window this board lives in. The date is not decoration:
    three 'Sat's on one ticket can be three different Saturdays."""
    from datetime import datetime, timedelta
    d = datetime.strptime(utc, "%Y-%m-%dT%H:%MZ") - timedelta(hours=4)
    return d.strftime("%a %-m/%-d %-I:%M%p").replace("AM", "am").replace("PM", "pm")
