"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-13 19:09Z from The Odds API, FanDuel prices only.
AWAY@HOME|Book|point|over|under. Monotonicity is asserted below at import time -- a broken ladder must crash, not price."""

TOTALS_RAW = """
CIN@CWS|FanDuel|13.5|-4000|1000
CIN@CWS|FanDuel|14.5|-800|450
CLE@DET|FanDuel|6.5|630|-1400
CLE@DET|FanDuel|7.5|920|-3500
CLE@DET|FanDuel|8.5|1280|-7000
PIT@MIA|FanDuel|5.5|-260|188
PIT@MIA|FanDuel|6.5|112|-148
PIT@MIA|FanDuel|7.5|230|-330
PIT@MIA|FanDuel|8.5|410|-700
PIT@MIA|FanDuel|9.5|750|-2000
PIT@MIA|FanDuel|10.5|1100|-4500
SEA@NYY|FanDuel|5.5|162|-225
SEA@NYY|FanDuel|6.5|230|-330
SEA@NYY|FanDuel|7.5|400|-670
SEA@NYY|FanDuel|8.5|580|-1200
SEA@NYY|FanDuel|9.5|880|-3000
SEA@NYY|FanDuel|10.5|1200|-5000
BOS@TOR|FanDuel|5.5|-275|198
BOS@TOR|FanDuel|6.5|-192|142
BOS@TOR|FanDuel|7.5|-108|-122
BOS@TOR|FanDuel|8.5|124|-166
BOS@TOR|FanDuel|9.5|194|-270
BOS@TOR|FanDuel|10.5|250|-360
BOS@TOR|FanDuel|11.5|390|-650
BOS@TOR|FanDuel|12.5|490|-900
BOS@TOR|FanDuel|13.5|680|-1600
CHC@WSH|FanDuel|6.5|-295|220
CHC@WSH|FanDuel|7.5|-174|136
CHC@WSH|FanDuel|8.5|-122|-104
CHC@WSH|FanDuel|9.5|128|-164
CHC@WSH|FanDuel|10.5|172|-225
CHC@WSH|FanDuel|11.5|250|-340
CHC@WSH|FanDuel|12.5|330|-480
CHC@WSH|FanDuel|13.5|470|-770
CHC@WSH|FanDuel|14.5|600|-1100
PHI@MIN|FanDuel|6.5|-280|210
PHI@MIN|FanDuel|7.5|-158|124
PHI@MIN|FanDuel|8.5|-111|-115
PHI@MIN|FanDuel|9.5|140|-180
PHI@MIN|FanDuel|10.5|190|-250
PHI@MIN|FanDuel|11.5|280|-390
PHI@MIN|FanDuel|12.5|350|-520
PHI@MIN|FanDuel|13.5|520|-900
PHI@MIN|FanDuel|14.5|680|-1400
TEX@LAA|FanDuel|6.5|-184|142
TEX@LAA|FanDuel|7.5|-108|-118
TEX@LAA|FanDuel|8.5|128|-164
TEX@LAA|FanDuel|9.5|200|-260
TEX@LAA|FanDuel|10.5|255|-350
TEX@LAA|FanDuel|11.5|370|-530
TEX@LAA|FanDuel|12.5|480|-800
TEX@LAA|FanDuel|13.5|680|-1400
TEX@LAA|FanDuel|14.5|900|-2500
MIL@LAD|FanDuel|6.5|-235|180
MIL@LAD|FanDuel|7.5|-140|110
MIL@LAD|FanDuel|8.5|100|-128
MIL@LAD|FanDuel|9.5|154|-200
MIL@LAD|FanDuel|10.5|210|-280
MIL@LAD|FanDuel|11.5|300|-430
MIL@LAD|FanDuel|12.5|400|-620
MIL@LAD|FanDuel|13.5|560|-1000
MIL@LAD|FanDuel|14.5|750|-1600
"""

GAME_OF = {}


def _dec(a):
    a = int(a)
    return 1 + (a / 100 if a > 0 else 100 / -a)

def _check_monotone(raw=None):
    from collections import defaultdict
    lad = defaultdict(list)
    for _l in (raw or TOTALS_RAW).strip().splitlines():
        if not _l.strip():
            continue
        _g, _bk, _pt, _ov, _un = _l.split('|')
        lad[(_g, _bk)].append((float(_pt), _dec(_ov), _dec(_un)))
    bad = []
    for _k, rungs in lad.items():
        rungs.sort()
        for (p0, o0, u0), (p1, o1, u1) in zip(rungs, rungs[1:]):
            if o1 <= o0:
                bad.append(f"{_k[0]} {_k[1]}: Over {p1} is not longer than Over {p0}")
            if u1 >= u0:
                bad.append(f"{_k[0]} {_k[1]}: Under {p1} is not shorter than Under {p0}")
    return bad

_bad = _check_monotone()
assert not _bad, ("totals.py ladder is not monotone -- these prices cannot all be "
                  "real:\n  " + "\n  ".join(_bad))
