"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-14 16:19Z from The Odds API, FanDuel prices only.
AWAY@HOME|Book|point|over|under. Monotonicity is asserted below at import time -- a broken ladder must crash, not price."""

TOTALS_RAW = """
STL@CHC|FanDuel|5.5|-340|250
STL@CHC|FanDuel|6.5|-230|176
STL@CHC|FanDuel|7.5|-130|102
STL@CHC|FanDuel|8.5|106|-136
STL@CHC|FanDuel|9.5|168|-220
STL@CHC|FanDuel|10.5|230|-310
STL@CHC|FanDuel|11.5|320|-460
STL@CHC|FanDuel|12.5|430|-670
STL@CHC|FanDuel|13.5|630|-1200
MIA@CIN|FanDuel|6.5|-215|164
MIA@CIN|FanDuel|7.5|-128|100
MIA@CIN|FanDuel|8.5|110|-140
MIA@CIN|FanDuel|9.5|172|-225
MIA@CIN|FanDuel|10.5|230|-310
MIA@CIN|FanDuel|11.5|320|-460
MIA@CIN|FanDuel|12.5|430|-670
MIA@CIN|FanDuel|13.5|600|-1100
MIA@CIN|FanDuel|14.5|800|-1800
BOS@PIT|FanDuel|5.5|-350|255
BOS@PIT|FanDuel|6.5|-235|182
BOS@PIT|FanDuel|7.5|-136|108
BOS@PIT|FanDuel|8.5|100|-128
BOS@PIT|FanDuel|9.5|158|-205
BOS@PIT|FanDuel|10.5|215|-290
BOS@PIT|FanDuel|11.5|300|-430
BOS@PIT|FanDuel|12.5|400|-620
BOS@PIT|FanDuel|13.5|560|-1000
CWS@DET|FanDuel|6.5|-295|220
CWS@DET|FanDuel|7.5|-172|134
CWS@DET|FanDuel|8.5|-122|-104
CWS@DET|FanDuel|9.5|132|-170
CWS@DET|FanDuel|10.5|176|-230
CWS@DET|FanDuel|11.5|255|-350
CWS@DET|FanDuel|12.5|330|-480
CWS@DET|FanDuel|13.5|480|-800
CWS@DET|FanDuel|14.5|600|-1100
BAL@TB|FanDuel|6.5|-245|186
BAL@TB|FanDuel|7.5|-142|112
BAL@TB|FanDuel|8.5|102|-130
BAL@TB|FanDuel|9.5|162|-210
BAL@TB|FanDuel|10.5|220|-295
BAL@TB|FanDuel|11.5|330|-480
BAL@TB|FanDuel|12.5|430|-670
BAL@TB|FanDuel|13.5|630|-1200
BAL@TB|FanDuel|14.5|830|-2000
SD@CLE|FanDuel|5.5|-265|200
SD@CLE|FanDuel|6.5|-180|140
SD@CLE|FanDuel|7.5|-106|-120
SD@CLE|FanDuel|8.5|132|-170
SD@CLE|FanDuel|9.5|215|-290
SD@CLE|FanDuel|10.5|285|-400
SD@CLE|FanDuel|11.5|400|-620
SD@CLE|FanDuel|12.5|520|-900
SD@CLE|FanDuel|13.5|750|-1600
WSH@NYM|FanDuel|6.5|-290|215
WSH@NYM|FanDuel|7.5|-166|130
WSH@NYM|FanDuel|8.5|-120|-106
WSH@NYM|FanDuel|9.5|132|-170
WSH@NYM|FanDuel|10.5|176|-230
WSH@NYM|FanDuel|11.5|255|-350
WSH@NYM|FanDuel|12.5|340|-500
WSH@NYM|FanDuel|13.5|480|-800
WSH@NYM|FanDuel|14.5|630|-1200
ARI@ATL|FanDuel|6.5|-245|186
ARI@ATL|FanDuel|7.5|-142|112
ARI@ATL|FanDuel|8.5|100|-128
ARI@ATL|FanDuel|9.5|152|-196
ARI@ATL|FanDuel|10.5|210|-280
ARI@ATL|FanDuel|11.5|300|-430
ARI@ATL|FanDuel|12.5|400|-620
ARI@ATL|FanDuel|13.5|560|-1000
ARI@ATL|FanDuel|14.5|750|-1600
NYY@TOR|FanDuel|5.5|-320|235
NYY@TOR|FanDuel|6.5|-215|164
NYY@TOR|FanDuel|7.5|-125|-102
NYY@TOR|FanDuel|8.5|112|-142
NYY@TOR|FanDuel|9.5|168|-220
NYY@TOR|FanDuel|10.5|230|-310
NYY@TOR|FanDuel|11.5|340|-500
NYY@TOR|FanDuel|12.5|440|-700
NYY@TOR|FanDuel|13.5|630|-1200
SEA@HOU|FanDuel|6.5|-250|190
SEA@HOU|FanDuel|7.5|-142|112
SEA@HOU|FanDuel|8.5|100|-128
SEA@HOU|FanDuel|9.5|152|-196
SEA@HOU|FanDuel|10.5|200|-265
SEA@HOU|FanDuel|11.5|300|-430
SEA@HOU|FanDuel|12.5|400|-620
SEA@HOU|FanDuel|13.5|560|-1000
SEA@HOU|FanDuel|14.5|750|-1600
KC@LAA|FanDuel|6.5|-290|215
KC@LAA|FanDuel|7.5|-164|128
KC@LAA|FanDuel|8.5|-115|-111
KC@LAA|FanDuel|9.5|136|-174
KC@LAA|FanDuel|10.5|186|-245
KC@LAA|FanDuel|11.5|280|-390
KC@LAA|FanDuel|12.5|350|-520
KC@LAA|FanDuel|13.5|500|-850
KC@LAA|FanDuel|14.5|630|-1200
TEX@ATH|FanDuel|7.5|-225|172
TEX@ATH|FanDuel|8.5|-164|128
TEX@ATH|FanDuel|9.5|-104|-122
TEX@ATH|FanDuel|10.5|126|-162
TEX@ATH|FanDuel|11.5|190|-250
TEX@ATH|FanDuel|12.5|240|-330
TEX@ATH|FanDuel|13.5|340|-500
TEX@ATH|FanDuel|14.5|450|-720
TEX@ATH|FanDuel|15.5|600|-1100
MIL@LAD|FanDuel|5.5|-310|230
MIL@LAD|FanDuel|6.5|-210|162
MIL@LAD|FanDuel|7.5|-122|-104
MIL@LAD|FanDuel|8.5|114|-146
MIL@LAD|FanDuel|9.5|172|-225
MIL@LAD|FanDuel|10.5|230|-310
MIL@LAD|FanDuel|11.5|320|-460
MIL@LAD|FanDuel|12.5|400|-620
MIL@LAD|FanDuel|13.5|600|-1100
COL@SF|FanDuel|5.5|-290|215
COL@SF|FanDuel|6.5|-188|146
COL@SF|FanDuel|7.5|-113|-113
COL@SF|FanDuel|8.5|124|-158
COL@SF|FanDuel|9.5|190|-250
COL@SF|FanDuel|10.5|250|-340
COL@SF|FanDuel|11.5|360|-530
COL@SF|FanDuel|12.5|480|-850
COL@SF|FanDuel|13.5|680|-1400
"""

GAME_OF = {}


def _dec(a):
    a = int(a)
    return 1 + (a / 100 if a > 0 else 100 / -a)

def _check_monotone(raw=None):
    from collections import defaultdict
    lad = defaultdict(list)
    for _l in (raw or TOTALS_RAW).strip().splitlines():
        if not _l.strip():
            continue
        _g, _bk, _pt, _ov, _un = _l.split('|')
        lad[(_g, _bk)].append((float(_pt), _dec(_ov), _dec(_un)))
    bad = []
    for _k, rungs in lad.items():
        rungs.sort()
        for (p0, o0, u0), (p1, o1, u1) in zip(rungs, rungs[1:]):
            if o1 <= o0:
                bad.append(f"{_k[0]} {_k[1]}: Over {p1} is not longer than Over {p0}")
            if u1 >= u0:
                bad.append(f"{_k[0]} {_k[1]}: Under {p1} is not shorter than Under {p0}")
    return bad

_bad = _check_monotone()
assert not _bad, ("totals.py ladder is not monotone -- these prices cannot all be "
                  "real:\n  " + "\n  ".join(_bad))
