"""GENERATED by pull_feeds.py — do not hand-edit; the next pull overwrites this file.
Generated 2026-08-04 19:05Z from The Odds API, FanDuel prices only.
AWAY@HOME|Book|point|over|under. Monotonicity is asserted below at import time -- a broken ladder must crash, not price."""

TOTALS_RAW = """
LAA@BAL|FanDuel|6.5|-370|265
LAA@BAL|FanDuel|7.5|-215|164
LAA@BAL|FanDuel|8.5|-158|124
LAA@BAL|FanDuel|9.5|102|-130
LAA@BAL|FanDuel|10.5|140|-180
LAA@BAL|FanDuel|11.5|200|-265
LAA@BAL|FanDuel|12.5|260|-360
LAA@BAL|FanDuel|13.5|370|-560
LAA@BAL|FanDuel|14.5|500|-850
ATH@CIN|FanDuel|7.5|-188|146
ATH@CIN|FanDuel|8.5|-138|108
ATH@CIN|FanDuel|9.5|116|-148
ATH@CIN|FanDuel|10.5|154|-200
ATH@CIN|FanDuel|11.5|230|-310
ATH@CIN|FanDuel|12.5|300|-430
ATH@CIN|FanDuel|13.5|420|-650
ATH@CIN|FanDuel|14.5|540|-950
ATH@CIN|FanDuel|15.5|750|-1600
NYM@CLE|FanDuel|5.5|-250|190
NYM@CLE|FanDuel|6.5|-172|134
NYM@CLE|FanDuel|7.5|100|-128
NYM@CLE|FanDuel|8.5|140|-180
NYM@CLE|FanDuel|9.5|215|-290
NYM@CLE|FanDuel|10.5|285|-400
NYM@CLE|FanDuel|11.5|420|-650
NYM@CLE|FanDuel|12.5|540|-950
NYM@CLE|FanDuel|13.5|800|-1800
WSH@PHI|FanDuel|6.5|-295|220
WSH@PHI|FanDuel|7.5|-174|136
WSH@PHI|FanDuel|8.5|-125|-102
WSH@PHI|FanDuel|9.5|124|-160
WSH@PHI|FanDuel|10.5|168|-220
WSH@PHI|FanDuel|11.5|240|-330
WSH@PHI|FanDuel|12.5|320|-460
WSH@PHI|FanDuel|13.5|440|-700
WSH@PHI|FanDuel|14.5|560|-1000
STL@NYY|FanDuel|6.5|-250|190
STL@NYY|FanDuel|7.5|-148|116
STL@NYY|FanDuel|8.5|-104|-122
STL@NYY|FanDuel|9.5|146|-188
STL@NYY|FanDuel|10.5|200|-265
STL@NYY|FanDuel|11.5|290|-410
STL@NYY|FanDuel|12.5|390|-590
STL@NYY|FanDuel|13.5|540|-950
STL@NYY|FanDuel|14.5|750|-1600
CWS@BOS|FanDuel|7.5|-186|144
CWS@BOS|FanDuel|8.5|-136|106
CWS@BOS|FanDuel|9.5|118|-150
CWS@BOS|FanDuel|10.5|158|-205
CWS@BOS|FanDuel|11.5|230|-310
CWS@BOS|FanDuel|12.5|300|-430
CWS@BOS|FanDuel|13.5|420|-650
CWS@BOS|FanDuel|14.5|540|-950
CWS@BOS|FanDuel|15.5|750|-1600
MIA@ATL|FanDuel|7.5|-215|164
MIA@ATL|FanDuel|8.5|-150|118
MIA@ATL|FanDuel|9.5|102|-130
MIA@ATL|FanDuel|10.5|134|-172
MIA@ATL|FanDuel|11.5|200|-265
MIA@ATL|FanDuel|12.5|255|-350
MIA@ATL|FanDuel|13.5|350|-520
MIA@ATL|FanDuel|14.5|450|-720
MIA@ATL|FanDuel|15.5|630|-1200
PIT@MIL|FanDuel|5.5|-280|210
PIT@MIL|FanDuel|6.5|-188|146
PIT@MIL|FanDuel|7.5|-113|-113
PIT@MIL|FanDuel|8.5|126|-162
PIT@MIL|FanDuel|9.5|200|-265
PIT@MIL|FanDuel|10.5|260|-360
PIT@MIL|FanDuel|11.5|390|-590
PIT@MIL|FanDuel|12.5|520|-900
PIT@MIL|FanDuel|13.5|750|-1600
MIN@KC|FanDuel|7.5|-220|168
MIN@KC|FanDuel|8.5|-162|126
MIN@KC|FanDuel|9.5|102|-130
MIN@KC|FanDuel|10.5|136|-174
MIN@KC|FanDuel|11.5|200|-265
MIN@KC|FanDuel|12.5|260|-360
MIN@KC|FanDuel|13.5|360|-530
MIN@KC|FanDuel|14.5|470|-770
MIN@KC|FanDuel|15.5|680|-1400
LAD@CHC|FanDuel|6.5|-350|255
LAD@CHC|FanDuel|7.5|-205|158
LAD@CHC|FanDuel|8.5|-146|114
LAD@CHC|FanDuel|9.5|106|-136
LAD@CHC|FanDuel|10.5|142|-184
LAD@CHC|FanDuel|11.5|200|-280
LAD@CHC|FanDuel|12.5|280|-390
LAD@CHC|FanDuel|13.5|370|-560
LAD@CHC|FanDuel|14.5|470|-770
SF@TEX|FanDuel|5.5|-330|240
SF@TEX|FanDuel|6.5|-215|164
SF@TEX|FanDuel|7.5|-128|100
SF@TEX|FanDuel|8.5|114|-146
SF@TEX|FanDuel|9.5|176|-230
SF@TEX|FanDuel|10.5|235|-320
SF@TEX|FanDuel|11.5|350|-520
SF@TEX|FanDuel|12.5|450|-720
SF@TEX|FanDuel|13.5|630|-1200
TOR@HOU|FanDuel|6.5|-260|196
TOR@HOU|FanDuel|7.5|-150|118
TOR@HOU|FanDuel|8.5|-108|-118
TOR@HOU|FanDuel|9.5|142|-184
TOR@HOU|FanDuel|10.5|190|-260
TOR@HOU|FanDuel|11.5|285|-400
TOR@HOU|FanDuel|12.5|360|-530
TOR@HOU|FanDuel|13.5|520|-900
TOR@HOU|FanDuel|14.5|680|-1400
TB@COL|FanDuel|8.5|-280|210
TB@COL|FanDuel|9.5|-180|138
TB@COL|FanDuel|10.5|-136|106
TB@COL|FanDuel|11.5|106|-136
TB@COL|FanDuel|12.5|140|-180
TB@COL|FanDuel|13.5|200|-265
TB@COL|FanDuel|14.5|250|-340
TB@COL|FanDuel|15.5|340|-500
TB@COL|FanDuel|16.5|430|-670
SD@ARI|FanDuel|7.5|-180|140
SD@ARI|FanDuel|8.5|-130|102
SD@ARI|FanDuel|9.5|122|-156
SD@ARI|FanDuel|10.5|162|-210
SD@ARI|FanDuel|11.5|235|-320
SD@ARI|FanDuel|12.5|300|-430
SD@ARI|FanDuel|13.5|420|-650
SD@ARI|FanDuel|14.5|540|-950
SD@ARI|FanDuel|15.5|750|-1600
DET@SEA|FanDuel|6.5|-205|158
DET@SEA|FanDuel|7.5|-120|-106
DET@SEA|FanDuel|8.5|120|-154
DET@SEA|FanDuel|9.5|196|-260
DET@SEA|FanDuel|10.5|260|-360
DET@SEA|FanDuel|11.5|390|-590
DET@SEA|FanDuel|12.5|500|-850
DET@SEA|FanDuel|13.5|750|-1600
DET@SEA|FanDuel|14.5|900|-2500
"""

GAME_OF = {}


def _dec(a):
    a = int(a)
    return 1 + (a / 100 if a > 0 else 100 / -a)

def _check_monotone(raw=None):
    from collections import defaultdict
    lad = defaultdict(list)
    for _l in (raw or TOTALS_RAW).strip().splitlines():
        if not _l.strip():
            continue
        _g, _bk, _pt, _ov, _un = _l.split('|')
        lad[(_g, _bk)].append((float(_pt), _dec(_ov), _dec(_un)))
    bad = []
    for _k, rungs in lad.items():
        rungs.sort()
        for (p0, o0, u0), (p1, o1, u1) in zip(rungs, rungs[1:]):
            if o1 <= o0:
                bad.append(f"{_k[0]} {_k[1]}: Over {p1} is not longer than Over {p0}")
            if u1 >= u0:
                bad.append(f"{_k[0]} {_k[1]}: Under {p1} is not shorter than Under {p0}")
    return bad

_bad = _check_monotone()
assert not _bad, ("totals.py ladder is not monotone -- these prices cannot all be "
                  "real:\n  " + "\n  ".join(_bad))
